"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class mpc_lcmt(object):
    __slots__ = ["force"]

    __typenames__ = ["float"]

    __dimensions__ = [[4, 3]]

    def __init__(self):
        self.force = [ [ 0.0 for dim1 in range(3) ] for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(mpc_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        for i0 in range(4):
            buf.write(struct.pack('>3f', *self.force[i0][:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != mpc_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return mpc_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = mpc_lcmt()
        self.force = []
        for i0 in range(4):
            self.force.append(struct.unpack('>3f', buf.read(12)))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if mpc_lcmt in parents: return 0
        tmphash = (0x59ee9b6387ee79b3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if mpc_lcmt._packed_fingerprint is None:
            mpc_lcmt._packed_fingerprint = struct.pack(">Q", mpc_lcmt._get_hash_recursive([]))
        return mpc_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", mpc_lcmt._get_packed_fingerprint())[0]

